<HTML>
<HEAD>
  <TITLE>Mixter Documentation</TITLE>
</HEAD>
<BODY>
<P ALIGN="LEFT">
Matthew Drake and Ian Spivey - Team &amp;nbsp;<BR>
<BR>
<FONT SIZE="5">Online Alternatives:</FONT><BR><BR>
<UL>
 <LI><B>Mp3.com</B> - For users who want to download music, mp3.com is our biggest competitor. They have a huge advantage in terms of userbase and artistbase. However, our site isn't primarily aimed at the users browsing for music. Our site is more aimed at the musician community, and mp3.com doesn't particular support that community at all. (Lack of magnet content, no forums, and no extensibility). Mp3 does have a very good organization system, and searching for content is powerful and easy. Mp3.com has an annoying user registration system - you must enter your email address just to download music. This is stupid and should not be there. There is little in the way of customizability after you've entered your email address, except specifying whether you like the high bandwidth or low bandwidth streams. Mp3.com does have a WAP interface which is fairly user friendly, although there are a few buggy links.
 <LI><B>Opsound</B> - Opsound is another site based on Creative Commons licenses for music distribution, and it's model for giving away music is the most like ours. Their site also is supposed to encourage artist collaboration, but they lack a forum structure, and there is little technology in place to encourage collaboration - it seems to be an extremely lightweight version of Mixter, and is more directly in competition with Mp3.com. Our contact at Creative Commons doesn't really regard this other site as a competitor, but suggests we advertise on their site for Mixter. If Mixter takes off, artists might use Mixter to develop their music, and then publish it on Opsound. So the two sites are more co-collaborators. It is worth noting that Opsound doesn't have a good search mechanism. You can go through indexes of titles, or artists, but the general purpose search just uses Google. This doesn't work that well because if you want to search you want to search for "guitar" or "techno," and you want artists or songs to be returned, not a list of webpages which google thinks might have to do with techno. As such, the search mechanism felt very clunky. Opsound has no user registration unless you are an artist, and this is horribly ugly. The form is ridiculously long, requiring you to include your sound files and the URLs to the sound files, and then when you submit it, you are told that your page will be made by the staff, and they will get back to you as soon as possible. This is not what is properly considered a "usable interface." Opsound does not have a WAP interface.
 <LI><B>rec.music.makers</B> - In this category I include both these, and a variety of public message boards maintained by ICQ. These message boards right now are the main community for musicians to talk to each other. They are likely to remain very popular; Getting their userbase to move over to using Mixter's forums is going to be one of the bigger hurdles. The google groups, usenet, and ICQ lists lack any sort of filespace though - there is no way for users to post files and ask for comments, or to post files and share them with some users, without making them public to everyone. Google search works fine for browsing through these archives.
 <LI><B>Specialized Websites</B> - There are a lot of specialized websites that contain information about "Live Bands in New Jersey," "Guitar Tabs," "Omaha Music Teacher directory," etc, but very little generalized information. Right now the only way to find this information is to search through usenet postings. One way Mixter could build a lot of content is simply by collecting a lot of these links and organizing them in some easy-to-search fashion.
</UL>
<P ALIGN="LEFT">
<A HREF="mailto:madrake@mit.edu">madrake@mit.edu</A></P>
</BODY>
</HTML>
