</div>

		<div id="footer"><img src="/images/footer.gif" alt="" width="760" /></div>
		<div id="subfooter"><a href="http://creativecommons.org/">Creative Commons</a> | <a href="http://sourceforge.net/tracker/?group_id=80503&atid=559966">report bugs</a> | <a href="/url-add/">add a url</a></div>
		<div id="subfooter">
<p align="center">
<!-- Creative Commons License -->
<a rel="license" href="http://creativecommons.org/licenses/GPL/2.0/"><img alt="CC-GNU GPL" border="0" src="http://creativecommons.org/images/public/cc-GPL.png" /></a><br />
This <a href="http://cctools.sourceforge.net">software</a> is licensed under the <a rel="license" href="http://creativecommons.org/licenses/GPL/2.0/">CC-GNU GPL</a>.
<!-- /Creative Commons License -->


<!--

<rdf:RDF xmlns="http://web.resource.org/cc/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<Work rdf:about="">
   <license rdf:resource="http://creativecommons.org/licenses/GPL/2.0/" />
</Work>

<License rdf:about="http://creativecommons.org/licenses/GPL/2.0/">
   <permits rdf:resource="http://web.resource.org/cc/Reproduction" />
   <permits rdf:resource="http://web.resource.org/cc/Distribution" />
   <requires rdf:resource="http://web.resource.org/cc/Notice" />
   <permits rdf:resource="http://web.resource.org/cc/DerivativeWorks" />
   <requires rdf:resource="http://web.resource.org/cc/ShareAlike" />
   <requires rdf:resource="http://web.resource.org/cc/SourceCode" />
</License>

</rdf:RDF>

-->
</p>
		</div>
		
	</div>
</body>
</html>
