<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style type="text/css">
		body {
			background:#eee;
			font-family: "Trebuchet MS",verdana,sans-serif; 
			font-size: 12px;
			color:#333;
		}
	
		#container {
			width: 760px;
			margin: 0px;
			margin-left: auto;
			margin-right: auto;
			padding: 0px;
		}

		#banner {
			padding: 0px;
			margin-bottom: 0px;
		background: #fff url(/images/background.gif) repeat-y 50% 0;		
		}

		#content {
			padding: 20px;
			margin-top:0px;
			background: #fff url(/images/background.gif) repeat-y 50% 0;
			}

		.searchbox {
			margin-left:50px;
			margin-right:50px;
			margin-bottom:50px;
			text-align:center;
		}			
		
		.resultsbox {
			margin-left:50px;
			margin-right:50px;
			margin-bottom:50px;
			text-align:left;
		}
			
		h1 {
			font-size:18px;
			font-family:Georgia;
			color:#666;
		}	
		
		h1 a {
			text-decoration:none;
			}
		
		#footer {
			clear: both;
			padding:0px;
			margin-top:0px;
		}
		
		#subfooter a {
			color:#999;
		}

		#subfooter {
			margin-left:10px;
			font-size:11px;
			color:#999;
		}
		
		.box {
			width:450px;
		}
		
		.searchhelp {
			margin:50px 50px 10px 50px;
			font-size:11px;
			border:1px solid #ccc;
			padding-left:20px;
			padding-right:20px;
			color:#666;
		}
		
		.searchform {
			margin-bottom:50px;
		}
		
		.notes {
			font-size:11px;
			color:green;
		}
		
		.searchtitle {
			font-size:16px;
		}
		
		.searchoptions {
			margin-top:10px;
		}
		
		a:link {color:#a00;}
		a:visited {color:#815151;}
		a:active {color:red;}
		a:hover {color:red;text-decoration:underline;}
	</style>
<title>RDF-enhanced search PROTOTYPE | Creative Commons</title>
<link rel="icon" href="http://creativecommons.org/includes/cc.ico" type="image/ico" />
<link rel="SHORTCUT ICON" href="http://creativecommons.org/includes/cc.ico" />
</head>
<body>
	<div id="container">
		<div id="banner">
		<img src="/images/top.gif" alt="" width="760" /><br />
		<a href="/"><img src="/images/header.gif" width="760" alt="" border="0" /></a>	
		</div>

<div id="content">
